from Exc2.classes_Stores import *
from Exc2.classes_Goods import *

grocery_store = GroceryStore()
hardware_store = HardwareStore()
apple = Apple(10)
lemon = Lemon(10)
banana = Banana(10)
green_banana = Banana(20)
nail = Nail(20)
axe = Axe(20)
hammer = Hammer(20)
apple.price
# lemon.price = 200 !!!
apple.set_discount(10)
banana.set_discount(10)
lemon.set_discount(10)
grocery_store.add_item(apple)
grocery_store.add_items(banana, nail, lemon, green_banana)
grocery_store.add_item(nail)
grocery_store.show_all_items()
grocery_store.remove_item(nail)
grocery_store.remove_item(banana)
grocery_store.show_all_items()
grocery_store.show_overall_price_no_discount()
grocery_store.show_overall_price_with_discount()
grocery_store.show_all_items()
nail.set_discount(10)
axe.set_discount(10)
hammer.set_discount(10)
hardware_store.add_item(nail)
hardware_store.add_items(hammer, axe, banana)
hardware_store.show_all_items()
hardware_store.show_overall_price_no_discount()
hardware_store.show_overall_price_with_discount()